name: ci

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: test ccache on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: List contents
        working-directory: /usr/local/
        run: find .
