name: Check Hostname

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-hostname:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]

    steps:
      - uses: actions/checkout@v3

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"

      - name: Run hostname check script
        run: |
          echo "Hostname: $(hostname)"
          echo "Fully Qualified Domain Name: $(hostname -f)"
          ping -c 1 localhost
          ping -c 1 $(hostname)
          ping -c 1 $(hostname -f)
        if: runner.os == 'macOS'

      - name: Run hostname check script
        run: |
          echo "Hostname: $(hostname)"
          echo "Fully Qualified Domain Name: $(hostname -f)"
          ping -c 1 localhost
          ping -c 1 $(hostname)
          ping -c 1 $(hostname -f)
        if: runner.os == 'Linux'

      - name: Run hostname check script
        run: |
          echo "Hostname: $(hostname)"
          echo "Fully Qualified Domain Name: $(hostname -f)"
          ping -n 1 localhost
          ping -n 1 $(hostname)
          ping -n 1 $(hostname -f)
        if: runner.os == 'Windows'
