name: Check Hostname

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-hostname:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run check-hostname.py
        run: python check-hostname.py

      - name: Run hostname check script
        run: |
          echo "Hostname: $(hostname)"
          echo "Fully Qualified Domain Name: $(hostname -f)"
          echo "Pinging localhost..."
          ping -c 1 localhost
          echo "Pinging hostname..."
          ping -c 1 $(hostname)
          echo "Pinging FQDN..."
          ping -c 1 $(hostname -f)
        if: runner.os == 'macOS'

      - name: Run hostname check script
        run: |
          echo "Hostname: $(hostname)"
          echo "Fully Qualified Domain Name: $(hostname -f)"
          echo "Pinging localhost..."
          ping -c 1 localhost
          echo "Pinging hostname..."
          ping -c 1 $(hostname)
          echo "Pinging FQDN..."
          ping -c 1 $(hostname -f)
        if: runner.os == 'Linux'

      - name: Run hostname check script
        run: |
          echo "Hostname: $env:COMPUTERNAME"
          echo "Fully Qualified Domain Name: $([System.Net.Dns]::GetHostByName($env:COMPUTERNAME).HostName)"
          echo "Pinging localhost..."
          ping -n 1 localhost
          echo "Pinging hostname..."
          ping -n 1 $env:COMPUTERNAME
          echo "Pinging FQDN..."
          ping -n 1 $([System.Net.Dns]::GetHostByName($env:COMPUTERNAME).HostName)
        shell: pwsh
        if: runner.os == 'Windows'
